---
title: "Dplyr graded lab"
author: "Louise Cazalet Dance"
format: html
editor: visual
---

```{r}
# Necessary packages 
library(readr)
library(dplyr)
library(tidyr)
library(vroom)
library(here)
library (knitr)
library(ggplot2)
library(lubridate)

here::i_am("eval-grades.Rproj")
```


## Introduction

### Study organization 

#### Question 1

```{r}
courses <- vroom(
  here("data", "courses.csv"))
```
##### Question 2

```{r}
courses |>
  rename(
  `course name` = course,
  identifier = course_id,
  `number of grades` = nb_grades
) |>
  arrange(`course name`) |>
  kable()
```

### Students

#### Question 3

```{r}
students <- vroom(
  here("data", "students.csv"))

students <- students |>
  mutate(
    birth_date = as.Date(birth_date),  
    sex = factor(sex),                
    group = factor(group),             
    id = as.integer(id)               
  )

birth_date_class <- class(students$birth_date)
sex_class <- class(students$sex)


```
The birth_date column of the students data frame is of class `{r} birth_date_class`.

The sex column of the students data frame is of class `{r} sex_class`.

### Grades

#### Question 4

```{r}
grades <- vroom(
  here("data", "grades.csv"),
  delim = "|",   
  na = "_"      
)

```
NE PAS OUBLIER D'ENLEVER LES WARNING A LA FIN

## Student population

### Question 5

```{r}

students_count <- students |>
  group_by(group) |>
  summarise(n_students = n())

ggplot(students_count, aes(x = group, y = n_students)) +
  geom_col(fill = "orange") +
  labs(
    title = "Number of Students per Group",
    x = "Group",
    y = "Number of Students"
  )
```

### Question 6

```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "fill") +  
  scale_y_continuous(labels = scales::percent_format()) +
  labs(
    title = "Gender Balance per Group",
    x = "Group",
    y = "Proportion of Students",
    fill = "Sex"
  )
```

### Question 7

```{r}

students <- students |>
  mutate(
    age = floor(time_length(today() - birth_date, unit = "year"))
  )


students |>
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "pink") +
  labs(
    title = "Distribution of Student Ages",
    x = "Age (years)",
    y = "Number of Students"
  )

```

